import react from 'react'

const AllInOne = react.createContext({
    userId:'',
    restaurantDetails: '',
    menuData: '',
    menuDataStatus: '',
    tablesData: '',
    tablesDataStatus: '',
    areasData: '',
    areasDataStatus: '',
    staffData: '',
    staffDataStatus: '',
    menuCategories: '',
    menuCategoriesStatus: '',
    orders: [],
    currentMenu: '',
    clickedOrder: '',
    updateClickedOrder: () => {},
    updateCurrentMenu:() => {},
    ordersStatus:'',
    updateOrdersStatus: () => {},
    newOrderReceived:false,
    addingMenuFun: () => {},
    updateMenuItem:() => {},
    deleteMenuItem: () => {},
    addMenuCategory: () => {},
    updateMenuCategory: () => {},
    deleteMenuCategory: () => {},
    addTable: () => {},
    updateTable: () => {},
    deleteTable: () => {},
    addArea:() => {},
    updateArea:() => {},
    deleteArea:() => {},
    addMenuInPOS: () => {},
    openAddMenuForPOSInMenuPage: false,
    fncOpenAddMenuForPOSInMenuPage: () => {},
})

export default AllInOne